// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjsxvxtsrmvurbwblcbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhqc3h2eHRzcm12dXJid2JsY2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjUxMjMsImV4cCI6MjA2MzU0MTEyM30.ShfC2I2MZR87ObShmtNkNTNIkhvkY7FBsiGXHHg9b3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});